#=====================================================#
#================= Configuration v2 ==================#
#=====================================================#

#=================== Global configuration ============#
#url=https://magento.softwaretestingboard.com
capabilities.browserName=safari
capabilities.browserVersion=NULL
#selenium_url=http://localhost:4444/wd/hub
custom_capabilities=NULL
extra_capabilities=NULL
app_version=


#=============== Environment configuration ===========#
env=DEMO
DEMO.base=https://www.gsmarena.com
DEMO.api_url=https://api.github.com
STAG.api_url=
#=====================================================#

#============== Locale Configurations ================#
locale=en_US
browser_language=en_US
localization_testing=false
localization_encoding=UTF-8
language=en_US
#=====================================================#

#uncomment and change udid and deviceName for Android test
#============ Android Local Mobile ===================#
#selenium_url=http://localhost:4723/
#capabilities.automationName=uiautomator2
#capabilities.deviceName=emulator-5554
#capabilities.udid=emulator-5554
#capabilities.deviceType=phone
#capabilities.platformName=ANDROID
#capabilities.appPackage=com.swaglabsmobileapp
#capabilities.appActivity=com.swaglabsmobileapp.MainActivity
#capabilities.app=/Users/ada1/Solvd/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk
#capabilities.app=https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.apk
#=====================================================#

#uncomment and change deviceName and platformVersion for iOS test
#======== Local Run for iOS Mobile ===============#
selenium_url=http://localhost:4723/
capabilities.platformName=iOS
capabilities.deviceName=iPhone16
capabilities.deviceType=phone
capabilities.platformVersion=18.1
capabilities.automationName=XCUITest
capabilities.udid=DDDF6C02-CCB7-4DDB-9FDB-939DB5DC43D7
#capabilities.appPackage=com.swaglabsmobileapp
#capabilities.appActivity=com.swaglabsmobileapp.MainActivity
#capabilities.app=/Users/ada1/Solvd/iOS.Simulator.SauceLabs.Mobile.Sample.app.2.7.1.zip
#capabilities.app=https://qaprosoft.s3-us-west-2.amazonaws.com/carinademoexample.zip
#=====================================================#